---
formatter: markdown table

header-from: main.tf
# (// FIXME: Remove, refactor or change. (Template)
content: |-
    # ☁️ AWS ECR Container Registry
    ## Description
    {{ .Header }}
    This module creates one or many ECR container registry, with the following capabilities:
    * 🚀 Create the ECR container registry.
    * 🚀 Create lifecycle policies. This option is optional, and disable by default.

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/ecr/basic/main.tf" }}
    ```

    An example that implement a more complex ECR repository, with lifecycle policies on it
    ```hcl
    {{ include "../../examples/ecr/basic/config/fixtures-lifecycle-policies.tfvars" }}
    ```

    An example that implement more than one (in this case, two) ECR repositories, with lifecycle policies on it
    ```hcl
    {{ include "../../examples/ecr/basic/config/fixtures-complete.tfvars" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
