---
name: Auto Tag Release Stable

on:
    push:
        branches:
            - main
            - master
        paths-ignore:
            - CHANGELOG.md

defaults:
    run:
        shell: bash

jobs:

    generate-tag:
        runs-on: ubuntu-latest
        if: |
            ${{ github.event_name == 'push' && (contains(github.ref, 'main') || contains(github.ref, 'master')) }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'

            - name: Generate tag & bump version
              uses: anothrNick/github-tag-action@1.36.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
